/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moes.mod;
data moes.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 1 data
---------------------------------------------------------------------------------------------------------------------------------------*/
data building_dat/moesGC.dat
data building_dat/moesCE.dat
data building_dat/moesMA.dat
data building_dat/moesGR.dat
data building_dat/moesCM.dat
data building_dat/moesBI.dat
data building_dat/moesCH.dat
data building_dat/moesPH.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 2 data
---------------------------------------------------------------------------------------------------------------------------------------*/

data building_dat/moesBC.dat
data building_dat/moesCO.dat
data building_dat/moesBP.dat
data building_dat/moesBS.dat
data building_dat/moesTCV.dat
data building_dat/moesIN.dat
data building_dat/moesODY.dat
data building_dat/moesME.dat
data building_dat/moesAA.dat
data building_dat/moesEL.dat
data building_dat/moesPO.dat
data building_dat/moesCRPP.dat
data building_dat/moesMX.dat
data building_dat/moesBM.dat
data building_dat/moesDIA.dat
data building_dat/moesAI.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the boiler model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moesboiler.mod;
data moesboiler.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the PV model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moesPV.mod;
data moesPV.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the SOFC model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moesSOFC.mod;
data moesSOFC.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Set the grid parameters: resource flow and fmax
---------------------------------------------------------------------------------------------------------------------------------------*/
let  Flowout['Natgas','NatGasGrid'] := refSize;
let  Fmax['NatGasGrid'] := refSize;
let  Flowout['Electricity','ElecGridBuy'] := refSize;
let  Fmax['ElecGridBuy'] := refSize;
let  Flowin['Electricity','ElecGridSell'] := refSize;
let  Fmax['ElecGridSell'] := refSize;

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
option solver '/home/deifilia/AMPL/ampl_linux-intel64/cplex';											# choose the solver
option omit_zero_rows 1;										# to not display 0 in rows
option omit_zero_cols 1;										# to not display 0 in columns

/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display Edemand;
display Qheating;
display Qheatingdemand;
display Qheatingsupply;

display mult;
display mult_t;

display Flowin;
display Flowout;

display FlowInUnit;
display FlowOutUnit;

display Buildings;

display usedroofArea;

display InvCost;

display OpCost;

display use;

