/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moes.mod;
data ../Project2_MILP/moes.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Inclusion of other models
---------------------------------------------------------------------------------------------------------------------------------------*/


/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 1 data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/building_dat/moesGC.dat
data ../Project2_MILP/building_dat/moesCE.dat
data ../Project2_MILP/building_dat/moesMA.dat
data ../Project2_MILP/building_dat/moesGR.dat
data ../Project2_MILP/building_dat/moesCM.dat
data ../Project2_MILP/building_dat/moesBI.dat
data ../Project2_MILP/building_dat/moesCH.dat
data ../Project2_MILP/building_dat/moesPH.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 2 data
---------------------------------------------------------------------------------------------------------------------------------------*/

data ../Project2_MILP/building_dat/moesBC.dat
data ../Project2_MILP/building_dat/moesCO.dat
data ../Project2_MILP/building_dat/moesBP.dat
data ../Project2_MILP/building_dat/moesBS.dat
data ../Project2_MILP/building_dat/moesTCV.dat
data ../Project2_MILP/building_dat/moesIN.dat
data ../Project2_MILP/building_dat/moesODY.dat
data ../Project2_MILP/building_dat/moesME.dat
data ../Project2_MILP/building_dat/moesAA.dat
data ../Project2_MILP/building_dat/moesEL.dat
data ../Project2_MILP/building_dat/moesPO.dat
data ../Project2_MILP/building_dat/moesCRPP.dat
data ../Project2_MILP/building_dat/moesMX.dat
data ../Project2_MILP/building_dat/moesBM.dat
data ../Project2_MILP/building_dat/moesDIA.dat
data ../Project2_MILP/building_dat/moesAI.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the boiler model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesboiler.dat;
model ../Project2_MILP/moesboiler.mod;


/*---------------------------------------------------------------------------------------------------------------------------------------
Load the PV model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesPV.dat;
model ../Project2_MILP/moesPV.mod;


/*---------------------------------------------------------------------------------------------------------------------------------------
Load the SOFC model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesSOFC.dat;
model ../Project2_MILP/moesSOFC.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the HP2stage model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
#data ../Project2_MILP/moesHP2stage.dat;
#model ../Project2_MILP/moesHP2stage.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the HP2stage_Carnot model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project5_Integration/moesHP2stage_Carnot.dat;
model ../Project5_Integration/moesHP2stage_Carnot.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the HP1stage models and their data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesHP1stageLT.dat;
model ../Project2_MILP/moesHP1stageLT.mod;


data ../Project2_MILP/moesHP1stageMT.dat;
model ../Project2_MILP/moesHP1stageMT.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the Cogen model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesCogen.dat;
model ../Project2_MILP/moesCogen.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the geothermal model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesGeothermal.dat;
model ../Project2_MILP/moesGeothermal.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Set the grid parameters: resource flow and fmax
---------------------------------------------------------------------------------------------------------------------------------------*/
let  Flowout['Natgas','NatGasGrid'] := refSize;
let  Fmax['NatGasGrid'] := refSize;
let  Flowout['Electricity','ElecGridBuy'] := refSize;
let  Fmax['ElecGridBuy'] := refSize;
let  Flowin['Electricity','ElecGridSell'] := refSize;
let  Fmax['ElecGridSell'] := refSize;

/*---------------------------------------------------------------------------------------------------------------------------------------
Integrate heat recovery results from part 3
----------------------------------------------------------------------------------------------------------------------------------------*/

let heat_recovery['DC', 1] := 357.011;
let heat_recovery['DC', 2] := 356.967;
let heat_recovery['DC', 3] := 335.21;
let heat_recovery['DC', 4] := 343.394;
let heat_recovery['DC', 5] := 0;
let heat_recovery['DC', 6] := 357.897;

let	heat_recovery['Vent', 1] := 0.549;
let	heat_recovery['Vent', 2] := 0.536;
let	heat_recovery['Vent', 3] := 0.263;
let	heat_recovery['Vent', 4] := 0.222;
let	heat_recovery['Vent', 5] := 0.131;
let	heat_recovery['Vent', 6] := 0.789;

let	heat_recovery['Vent_HP', 1] := 1577.79;
let	heat_recovery['Vent_HP', 2] := 1542.22;
let	heat_recovery['Vent_HP', 3] := 757.489;
let	heat_recovery['Vent_HP', 4] := 638.682;
let	heat_recovery['Vent_HP', 5] := 428.859;
let	heat_recovery['Vent_HP', 6] := 2023.78;

# COSTS and OBJECTIVE
let OPEX['DC'] := 769173;
let CAPEX['DC'] :=  11302.8;

let OPEX['Vent'] := 796379;
let CAPEX['Vent'] := 785.514;

let OPEX['Vent_HP'] := 693652;
let CAPEX['Vent_HP'] := 167257;


