/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model ../Project2_MILP/moes.mod;
data ../Project2_MILP/moes.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Inclusion of other models and data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moesP5.mod
data moesP5.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 1 data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/building_dat/moesGC.dat
data ../Project2_MILP/building_dat/moesCE.dat
data ../Project2_MILP/building_dat/moesMA.dat
data ../Project2_MILP/building_dat/moesGR.dat
data ../Project2_MILP/building_dat/moesCM.dat
data ../Project2_MILP/building_dat/moesBI.dat
data ../Project2_MILP/building_dat/moesCH.dat
data ../Project2_MILP/building_dat/moesPH.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 2 data
---------------------------------------------------------------------------------------------------------------------------------------*/

data ../Project2_MILP/building_dat/moesBC.dat
data ../Project2_MILP/building_dat/moesCO.dat
data ../Project2_MILP/building_dat/moesBP.dat
data ../Project2_MILP/building_dat/moesBS.dat
data ../Project2_MILP/building_dat/moesTCV.dat
data ../Project2_MILP/building_dat/moesIN.dat
data ../Project2_MILP/building_dat/moesODY.dat
data ../Project2_MILP/building_dat/moesME.dat
data ../Project2_MILP/building_dat/moesAA.dat
data ../Project2_MILP/building_dat/moesEL.dat
data ../Project2_MILP/building_dat/moesPO.dat
data ../Project2_MILP/building_dat/moesCRPP.dat
data ../Project2_MILP/building_dat/moesMX.dat
data ../Project2_MILP/building_dat/moesBM.dat
data ../Project2_MILP/building_dat/moesDIA.dat
data ../Project2_MILP/building_dat/moesAI.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the boiler model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesboiler.dat;
model ../Project2_MILP/moesboiler.mod;


/*---------------------------------------------------------------------------------------------------------------------------------------
Load the PV model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesPV.dat;
model ../Project2_MILP/moesPV.mod;


/*---------------------------------------------------------------------------------------------------------------------------------------
Load the SOFC model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesSOFC.dat;
model ../Project2_MILP/moesSOFC.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the HP2stage model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
#data ../Project2_MILP/moesHP2stage.dat;
#model ../Project2_MILP/moesHP2stage.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the HP2stage_Carnot model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project5_Integration/moesHP2stage_Carnot.dat;
model ../Project5_Integration/moesHP2stage_Carnot.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the HP1stage models and their data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesHP1stageLT.dat;
model ../Project2_MILP/moesHP1stageLT.mod;

data ../Project5_Integration/moesHP1stageLT_2.dat;
model ../Project5_Integration/moesHP1stageLT_2.mod;

data ../Project2_MILP/moesHP1stageMT.dat;
model ../Project2_MILP/moesHP1stageMT.mod;

data ../Project5_Integration/moesHP1stageMT_2.dat;
model ../Project5_Integration/moesHP1stageMT_2.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the Cogen model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesCogen.dat;
model ../Project2_MILP/moesCogen.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load the geothermal model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
data ../Project2_MILP/moesGeothermal.dat;
model ../Project2_MILP/moesGeothermal.mod;
