/*---------------------------------------------------------------------------------------------------------------------------------------
import all the model and data files for part 5
---------------------------------------------------------------------------------------------------------------------------------------*/
include import.run

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
option solver snopt;											# choose the solver
# option solver '/home/deifilia/AMPL/ampl_linux-intel64/snopt';
option presolve 10;
option snopt_options 'major_iterations=10000';

option omit_zero_rows 1;										# to not display 0 in rows
option omit_zero_cols 1;										# to not display 0 in columns
option log_file 'moes.log';

/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display Edemand;
display Qheating;
display Qheatingdemand;
display Qheatingsupply;

display mult;
display mult_t;

display Flowin;
display Flowout;

display FlowInUnit;
display FlowOutUnit;

display Buildings;

#display usedroofArea;

display InvCost;

display OpCost;

display use;

display Tlmc_HP1stageMT;

display CO2;

display heat_recovery;

display use_recovery;

display Improvements;