/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display Edemand;
display Qheating;
display Qheatingdemand;
display Qheatingsupply;

display mult;
display mult_t;

display Fmax;

display Flowin;
display Flowout;

display FlowInUnit;
display FlowOutUnit;

display usedroofArea;

display InvCost;
display OpCost;

display CO2;

display heat_recovery;
display use_recovery;

display FlowInUnitSum;
display FlowOutUnitSum;
