/*---------------------------------------------------------------------------------------------------------------------------------------
import all the model and data files for part 5
---------------------------------------------------------------------------------------------------------------------------------------*/
include import.run

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
#option solver snopt;											# choose the solver
option solver 'snopt';
option presolve 10;
option snopt_options 'major_iterations=10000';

option omit_zero_rows 1;										# to not display 0 in rows
option omit_zero_cols 1;										# to not display 0 in columns

#Scenario 1
minimize scenario1: InvCost;
objective scenario1;
solve;
option log_file 'scenario1.log';
include output.run

#Scenario 2
minimize scenario2 :OpCost;
objective scenario2;
solve;
option log_file 'scenario2.log';
include output.run
