/*---------------------------------------------------------------------------------------------------------------------------------------
import all the model and data files for part 5
---------------------------------------------------------------------------------------------------------------------------------------*/
include import.run

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
#option solver snopt;											# choose the solver
option solver 'snopt';
option presolve 10;
option snopt_options 'major_iterations=10000';

option omit_zero_rows 1;										# to not display 0 in rows
option omit_zero_cols 1;										# to not display 0 in columns
option log_file 'scenario.log';


#Scenario 1
minimize InvCost;
objective InvCost;
solve;
option log_file 'scenario1.log';

#Scenario 2
minimize OpCost;
objective OpCost;
solve;
option log_file 'scenario2.log';
