/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
reset;
model NLP_vent_HP.mod;
data  NLP_vent_HP.dat;

data ../../Project2_MILP/building_dat/moesGC.dat
data ../../Project2_MILP/building_dat/moesCE.dat
data ../../Project2_MILP/building_dat/moesMA.dat
data ../../Project2_MILP/building_dat/moesGR.dat
data ../../Project2_MILP/building_dat/moesCM.dat
data ../../Project2_MILP/building_dat/moesBI.dat
data ../../Project2_MILP/building_dat/moesCH.dat
data ../../Project2_MILP/building_dat/moesPH.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
option solver snopt;
 #option solver '/home/deifilia/AMPL/ampl_linux-intel64/snopt';
option presolve 5;
#option omit_zero_rows 1;
#option omit_zero_cols 1;
option presolve_eps 8.53e-15;
option snopt_options 'major_iterations=10000';
option log_file 'NLP_vent_HP.log';


/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display TC;
display OPEX;
display CAPEX;

display Qheating;

print '########################################';
print '#    HEAT EXCHANGER';
print '########################################';
display Area_Vent;
display Heat_Vent;
display theta_1;
display theta_2;

print '########################################';
print '#    AIR STREAM TEMPERATURES';
print '########################################';
print '##   incoming air stream';
display Text;
display Text_new;
display Tair_in;
print '##   outgoing air stream';
display Tint;
display Trelease;
display Trelease_2;

print '########################################';
print '#    AIR VENTILATION HEAT PUMP';
print '########################################';
print '##   powers';
display Qevap_2;
display Qcond_2;
display E_2;

print '##   temperatures / properties';
display COP_2;
display TLMCond_2;
display TLMEvapHP_2;

print '########################################';
print '#    MAIN HEAT PUMP';
print '########################################';
print '##   powers';
display Qevap;
display Qcond;
display E;

print '##   temperatures / properties';
display COP;
display TLMCond;
display TLMEvapHP;

# display Cost_HP;
