/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
reset;
model NLP_vent_HP.mod;
data  NLP_vent_HP.dat;

data ../../Project2_MILP/building_dat/moesGC.dat
data ../../Project2_MILP/building_dat/moesCE.dat
data ../../Project2_MILP/building_dat/moesMA.dat
data ../../Project2_MILP/building_dat/moesGR.dat
data ../../Project2_MILP/building_dat/moesCM.dat
data ../../Project2_MILP/building_dat/moesBI.dat
data ../../Project2_MILP/building_dat/moesCH.dat
data ../../Project2_MILP/building_dat/moesPH.dat

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
#option solver snopt;
option solver '/home/deifilia/AMPL/ampl_linux-intel64/snopt';
option presolve 2;
# option omit_zero_rows 1;
# option omit_zero_cols 1;
option presolve_eps 8.53e-15;
option snopt_options 'major_iterations=10000';
option log_file 'NLP_vent_HP.log';


/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display TC;
display OPEX;
display CAPEX;
display Profit;
display Paybt;

display Area_Vent;
display Qheating;
display Heat_Vent;
display Trelease;


display E;
display E_2;

display Text;
display Text_new;
display Tair_in;
display Trelease;
display Trelease_2;

display Qevap_2;
display Qcond_2;
display COP_2;
display TLMCond_2;
display TLMEvapHP_2;

display TLMCond;
display TLMEvapHP;

display Cost_HP;


