/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
reset;
model NLP_DC.mod;
data NLP_DC.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
option solver 'snopt';#'/home/deifilia/AMPL/ampl_linux-intel64/snopt';
option snopt_options 'major_iterations=10000';
#option omit_zero_rows 1;
#option omit_zero_cols 1;
option log_file 'NLP_DC.log';

/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
#These variables might be interest to print. Feel free to choose new ones!

display Qrad;
display TRadin;
display TDCout;
display AHEDC;
display dTLMDC;

display E;
display COP;

display Qcond;
display TLMCond;

display Qevap;
display TLMEvapHP;
display THPin;

display MassEPFL;
display MassDC;
display Qfree;
display Flow;

display TC;
display OPEX;
display CAPEX;

display Qheating;
display Qcond;
display Qrad;


